### ISSUE TITLE
Extra data in MemoryEvent

### ISSUE THREAD

**Issue by mspdevelopers** [distriqt/ANE-Memory#1]
Is it possible to attach the current memory usage in the MemoryEvent?

**Comment by marchbold** [comment]
Do you have any reference to exactly what memory values you want returned?

**Comment by mspdevelopers** [comment]
The current RAM value that provoked the event, can you get it from the device directly instead of from adobe air? Because you can't relay on System.privateMemory, System.usedMemory, etc.

**Comment by marchbold** [comment]
I'll have to do some research. I don't know of any easy API to access memory values. I think there are some on the NSProcessInfo class but I think the rest might require some c calls.
