### ISSUE TITLE
Rebuild this ane

### ISSUE THREAD

**Issue by xxxVBxxx** [distriqt/ANE-Memory#4]
Hello
Could you recreate this ANE? with AIR version 32
Thank you in advance

**Comment by marchbold** [comment]
What issue are you having with the ANE?

**Comment by xxxVBxxx** [comment]
Hello
1. when sending to the Appstore I get an error, as I understood it because of -ios_version_min
2. I stopped receiving a low-memory notification.
I want to check maybe because of the SDK version

**Comment by xxxVBxxx** [comment]
If it's not difficult for you, please make a new version, thanks in advance

**Comment by 3DtuningProduction** [comment]
Tnx))
