### ISSUE TITLE
Memory Android 64bit support

### ISSUE THREAD

**Issue by marchbold** [distriqt/ANE-Memory#5]
Update the extension to include support for Android 64bit

>
> Starting August 1, 2019, your apps published on Google Play will need to support 64-bit architectures. 64-bit CPUs deliver faster, richer experiences for your users. Adding a 64-bit version of your app provides performance improvements, makes way for future innovation, and sets you up for devices with 64-bit-only hardware.
>

**Comment by SpikeApp** [comment]
If you need support on how to use Spike or solve a specific issue please join our support group at https://www.facebook.com/groups/spikeapp/

We do NOT give one on one support by e-mail.

Thank you!

The Spike Team

**Comment by marchbold** [comment]
Beta: https://www.dropbox.com/s/xprcr779uzri2ub/com.distriqt.Memory.v3.0.001.zip?dl=0
